repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: check-json
    -   id: check-vcs-permalinks
    -   id: trailing-whitespace
        exclude: ^test/
-   repo: local
    hooks:
      - id: fmt
        name: fmt
        language: system
        types: [file, rust]
        entry: cargo fmt -- --check

      - id: clippy
        name: clippy
        language: system
        types: [file, rust]
        entry: cargo clippy --all-targets --all # -- -D warnings # Use -D warnings option to ensure the job fails when encountering warnings
        pass_filenames: false

      - id: test
        name: test
        language: system
        files: '\.rs$'
        entry: cargo test --lib
        pass_filenames: false

default_language_version:
    python: python3.7
