repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
    -   id: check-executables-have-shebangs
    -   id: check-merge-conflict
    -   id: check-symlinks
    -   id: check-yaml
    -   id: check-json
    -   id: check-vcs-permalinks
    -   id: trailing-whitespace
        exclude: ^test/
    -   id: mixed-line-ending
        exclude: ^test/
-   repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.30.0
    hooks:
    -   id: markdownlint
-   repo: https://github.com/DevinR528/cargo-sort
    rev: v1.0.6
    hooks:
    -   id: cargo-sort
-   repo: meta
    hooks:
    -   id: check-useless-excludes
-   repo: local
    hooks:
      - id: fmt
        name: fmt
        language: system
        types: [file, rust]
        entry: cargo fmt -- --check
        pass_filenames: false

      - id: clippy
        name: clippy
        language: system
        types: [file, rust]
        entry: cargo clippy --bins --tests --examples --all -- -D rust_2018_idioms # -- -D warnings # Use -D warnings option to ensure the job fails when encountering warnings
        pass_filenames: false

      - id: test
        name: test
        language: system
        types: [file, rust]
        entry: cargo test --lib
        pass_filenames: false

default_language_version:
    python: python3
