sudo: false
language: rust
matrix:
  include:
    - os: linux
      rust: stable
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - g++-5
            - libgoogle-perftools-dev
      env:
        - GCC_CXX=g++-5
        - GCOV=gcov-5
        - CLANG_CXX=clang++-7
        - CXX=clang++-7
        - DEPLOY=0

    - os: linux
      rust: nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - g++-5
            - libgoogle-perftools-dev
      env:
        - GCC_CXX=g++-5
        - GCOV=gcov-5
        - CLANG_CXX=clang++-7
        - CXX=clang++-7
        - DEPLOY=0

    - os: linux
      rust: nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - g++-6
            - libgoogle-perftools-dev
      env:
        - GCC_CXX=g++-6
        - GCOV=gcov-6
        - CLANG_CXX=clang++-7
        - CXX=clang++-7
        - DEPLOY=0

    - os: linux
      rust: nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-7
          packages:
            - clang-7
            - g++-7
            - libgoogle-perftools-dev
      env:
        - GCC_CXX=g++-7
        - GCOV=gcov-7
        - CLANG_CXX=clang++-7
        - CXX=clang++-7
        - DEPLOY=1

    - os: linux
      rust: nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-8
          packages:
            - clang-8
            - g++-7
            - libgoogle-perftools-dev
      env:
        - GCC_CXX=g++-7
        - GCOV=gcov-7
        - CLANG_CXX=clang++-8
        - CXX=clang++-8
        - DEPLOY=0

    - os: linux
      rust: nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty
          packages:
            - clang-9
            - g++-7
            - libgoogle-perftools-dev
      env:
        - GCC_CXX=g++-7
        - GCOV=gcov-7
        - CLANG_CXX=clang++-9
        - CXX=clang++-9
        - DEPLOY=0

    - os: linux
      rust: nightly
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - clang-10
            - g++-7
            - libgoogle-perftools-dev
      env:
        - GCC_CXX=g++-7
        - GCOV=gcov-7
        - CLANG_CXX=clang++-10
        - CXX=clang++-10
        - DEPLOY=0

    - os: linux
      rust: nightly
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-11
            - g++-7
            - libgoogle-perftools-dev
      env:
        - GCC_CXX=g++-7
        - GCOV=gcov-7
        - CLANG_CXX=clang++-11
        - CXX=clang++-11
        - DEPLOY=0

    - os: linux
      rust: nightly
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/bionic/ llvm-toolchain-bionic-11 main'
              key_url: 'https://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - clang-11
            - g++-10
            - libgoogle-perftools-dev
      env:
        - GCC_CXX=g++-10
        - GCOV=gcov-10
        - CLANG_CXX=clang++-11
        - DEPLOY=0

    - os: osx
      rust: nightly
      env:
        - CLANG_CXX=clang++
        - DEPLOY=1

    - os: linux
      rust: stable
      dist: bionic
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - python3-pip
            - python3-setuptools
            - python3-wheel
      script:
        - rustup component add rustfmt clippy
        - pip3 install --disable-pip-version-check --quiet --no-cache-dir pre-commit
        - pre-commit run --all-files

install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then sudo softwareupdate -i "Command Line Tools (macOS High Sierra version 10.13) for Xcode-9.4"; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cask uninstall --force oclint; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gperftools; fi
script:
    - rustup component add llvm-tools-preview
    - $CLANG_CXX --version
    - |
      if [ "$TRAVIS_RUST_VERSION" = "nightly" ] && [ -z "$TRAVIS_TAG" ]; then
        export RUSTFLAGS="-Zinstrument-coverage";
      fi
    - if [ "$TRAVIS_TAG" ]; then export CARGO_OPTIONS="--release"; fi
    - cargo build --verbose $CARGO_OPTIONS
    - LLVM_PROFILE_FILE="grcov-%p-%m.profraw" cargo test --verbose $CARGO_OPTIONS
    - |
      if [ "$TRAVIS_RUST_VERSION" = "nightly" ] && [ -z "$TRAVIS_TAG" ]; then
        cargo run --release -- `find . \( -name "grcov-*.profraw" \) -print` --binary-path ./target/debug/ -s . -t lcov --branch --ignore-not-existing --ignore "/*" -o lcov.info;
        bash <(curl -s https://codecov.io/bash) -f lcov.info;
      fi
    - |
      if [ "$TRAVIS_TAG" ]; then
        export CARGO_OPTIONS="--release --features tc --target-dir tcmalloc_build";
        cargo build --verbose $CARGO_OPTIONS;
      fi
before_deploy:
    - tar -cvjSf grcov-${TRAVIS_OS_NAME}-x86_64.tar.bz2 -C target/release/ grcov
    - tar -cvjSf grcov-tcmalloc-${TRAVIS_OS_NAME}-x86_64.tar.bz2 -C tcmalloc_build/release/ grcov
deploy:
  api_key:
    secure: by7CZhF9PTfQMbIlOIO/AuhnNv6YhgXLgDuMJurW0Z/3fDuAQG0zRHYAdvgbvwVa0KTQWamJbo1HD9LYGdACwNyO4uJWN+Zek3p/OM+axTk3/UZlr3UnGizk3UHM/Z1+awHsMYghk4UoGc8795x3iZs+PF2+lqMHGgBfpWRP5IP5PHCX93D7W0myTi4c2hu8Ufb5rC44vQ2EvuThYiX3UQ2BQVv0jaRdp9hT5XChJH8fmGZRq46yK7XCpCWSKN+29dn3/5/4b2mLN7DaTQB60DFaQPZKORva4ISUByk4EnzI7JAW9/6yT2tsiwvUkZuKoPNyv4yPGqu/QdROriUajFeu8bLVfAkxzKjVYNU0Cu4NCC84VVf2rP6YxZwUXBnBRL9qTHYgZZ8MLRC43bPF9s4mI8XR02DQtC/xajgnusxL3qEovxNnETCC0xXdMqw063o37IQLa8XkdAvQ5fB4QBeiX+8YBZwIFZO3wXKFbCkbx7ocigpfBTMh7tNdK457n5o3NILMKL2SyibI0sriXZ7qJUDwUHSoECRfivjdkdgQMBqTaVQAsQIT9Cpm+G2DI1QPXJC8xtCqEpKjExNMQeOUChs43O7XqIt5TffP2U2cAuAQTJKDDrPzJLxWK7tNeU8crmBG1s4tQDJZki4JxPwLBrLInw3YC9TD3A3YA3Y=
  file:
    - grcov-${TRAVIS_OS_NAME}-x86_64.tar.bz2
    - grcov-tcmalloc-${TRAVIS_OS_NAME}-x86_64.tar.bz2
  on:
    rust: nightly
    tags: true
    condition: $DEPLOY = 1
  provider: releases
  skip_cleanup: true
