sudo: false
language: rust
matrix:
  include:
    - os: linux
      rust: stable
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - llvm-4.0-dev
            - clang-4.0
            - llvm-4.0
            - gcc-4.9
            - g++-4.9
      env:
        - COMPILER_VER=4.9

    - os: linux
      rust: nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - llvm-4.0-dev
            - clang-4.0
            - llvm-4.0
            - gcc-4.9
            - g++-4.9
      env:
        - COMPILER_VER=4.9

    - os: linux
      rust: nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - llvm-4.0-dev
            - clang-4.0
            - llvm-4.0
            - gcc-5
            - g++-5
      env:
        - COMPILER_VER=5

    - os: linux
      rust: nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - llvm-4.0-dev
            - clang-4.0
            - llvm-4.0
            - gcc-6
            - g++-6
      env:
        - COMPILER_VER=6

    - os: linux
      rust: nightly
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: 'deb http://apt.llvm.org/precise/ llvm-toolchain-precise-4.0 main'
              key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'
          packages:
            - llvm-4.0-dev
            - clang-4.0
            - llvm-4.0
            - gcc-7
            - g++-7
      env:
        - COMPILER_VER=7

    - os: osx
      rust: nightly
      env:
        - COMPILER_VER=7
install:
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew cask uninstall --force oclint; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install gcc; fi
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then brew install llvm@4 && brew link --overwrite --force llvm@4; fi
    - mkdir -p symlinks
    - ln -s /usr/bin/clang-4.0 symlinks/clang
    - ln -s /usr/bin/clang++-4.0 symlinks/clang++
    - ln -s /usr/bin/llvm-cov-4.0 symlinks/llvm-cov
    - ln -s /usr/bin/llvm-config-4.0 symlinks/llvm-config
    - ln -s `which gcc-${COMPILER_VER}` symlinks/gcc
    - ln -s `which g++-${COMPILER_VER}` symlinks/g++
    - ln -s `which gcov-${COMPILER_VER}` symlinks/gcov
script:
    - export PATH=$PWD/symlinks:$PATH
    - gcc --version
    - clang --version
    - if [ -z "$TRAVIS_TAG" ]; then cargo build --verbose; fi
    - if [ -z "$TRAVIS_TAG" ]; then cargo test -- --nocapture; fi
before_deploy:
    - cargo build --release --features=alloc_system
    - tar -cvjSf grcov-${TRAVIS_OS_NAME}-x86_64.tar.bz2 -C target/release/ grcov
deploy:
  api_key:
    secure: by7CZhF9PTfQMbIlOIO/AuhnNv6YhgXLgDuMJurW0Z/3fDuAQG0zRHYAdvgbvwVa0KTQWamJbo1HD9LYGdACwNyO4uJWN+Zek3p/OM+axTk3/UZlr3UnGizk3UHM/Z1+awHsMYghk4UoGc8795x3iZs+PF2+lqMHGgBfpWRP5IP5PHCX93D7W0myTi4c2hu8Ufb5rC44vQ2EvuThYiX3UQ2BQVv0jaRdp9hT5XChJH8fmGZRq46yK7XCpCWSKN+29dn3/5/4b2mLN7DaTQB60DFaQPZKORva4ISUByk4EnzI7JAW9/6yT2tsiwvUkZuKoPNyv4yPGqu/QdROriUajFeu8bLVfAkxzKjVYNU0Cu4NCC84VVf2rP6YxZwUXBnBRL9qTHYgZZ8MLRC43bPF9s4mI8XR02DQtC/xajgnusxL3qEovxNnETCC0xXdMqw063o37IQLa8XkdAvQ5fB4QBeiX+8YBZwIFZO3wXKFbCkbx7ocigpfBTMh7tNdK457n5o3NILMKL2SyibI0sriXZ7qJUDwUHSoECRfivjdkdgQMBqTaVQAsQIT9Cpm+G2DI1QPXJC8xtCqEpKjExNMQeOUChs43O7XqIt5TffP2U2cAuAQTJKDDrPzJLxWK7tNeU8crmBG1s4tQDJZki4JxPwLBrLInw3YC9TD3A3YA3Y=
  file: grcov-${TRAVIS_OS_NAME}-x86_64.tar.bz2
  on:
    rust: nightly
    tags: true
    condition: $COMPILER_VER = 7
  provider: releases
  skip_cleanup: true
